### ISSUE TITLE
Create a nightly build setup in Drone

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/ATT#4]
In order to solve #3 and to drop Jenkins, we should look into adding nightly builds to Drone instead. We need nightly builds for J3 and J4 and a documentation how this could be done for other repos (weblinks, search, etc.) as well.

**Comment by mbabker** [comment]
Unless your team moves the Drone architecture to the project's sponsored hosting, I'm saying no to your idea of replacing Jenkins.  The Jenkins platform is on the project's sponsored hosting with all appropriate security measures, which includes whitelisting rules to allow it access to the needed servers to do its job as it relates to publishing resources to `joomla.org` subdomains (which goes beyond just tasks related to the building and publishing of CMS related artifacts).  I am not about to agree to whitelist a third party server outside the project's oversight to be able to directly access the project's servers, this is a security risk beyond that which I am willing to accept.

**Comment by Hackwar** [comment]
I have no problem moving Drone to another server. I don't really see the difference between the sponsored server of Jenkins and the sponsored server of Drone right now, but if that is a requirement of yours, then we should respect that.

My ultimate goal is to reduce the number of CI systems that we are running. I admittedly have grown fond of Drone, but as long as we are reducing the list of Travis, Jenkins, Drone, Appveyor and Hound to something with less entries, I'm happy.

I also don't need that nightly setup to just generate the nightly builds which Jenkins currently creates, but to create the basis for the patchtester changes.

**Comment by mbabker** [comment]
I'm not detailing it on a public forum, but access to everything beyond ports 80 and 443 on the `joomla.org` servers is pretty restricted.  We don't have any third party systems which are whitelisted the access a CI job would need to publish the nightly builds to the Developer Network or deploy updates of various resources for the `joomla.org` subdomains (which is what Jenkins is primarily doing).  And I'd rather keep it that way, it should be a "project owned" resource if it's going to be whitelisted to have what is in essence shell access to the servers and to the best of my knowledge the infrastructure that Drone is deployed to is not "project owned".

**Comment by Hackwar** [comment]
Has been solved.
